version: "3.5"
services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rabbitmq
    ports:
        - "5672:5672"
        - "15672:15672"
        - "15671:15671"
    privileged: true
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
    volumes:
        - ~/.docker-conf/rabbitmq:/var/lib/rabbitmq
    networks:
        - shared      

networks:
  shared: 
    external:
      name: shared

      