version: '3'
services:
  db:
    image: mysql:8.0.23
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: earnings
      MYSQL_ROOT_PASSWORD: 123456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - shared
networks:
  shared: 
    external:
      name: shared   