version: '3'
services:
  master:
    image: redis
    container_name: redis-master
    command: redis-server --requirepass redis_pwd  --masterauth redis_pwd
    networks:
      - shared    
    ports:
      - 6379:6379
  slave1:
    image: redis
    container_name: redis-slave-1
    networks:
      - shared    
    ports:
      - 6380:6379
    command:  redis-server --slaveof redis-master 6379 --requirepass redis_pwd --masterauth redis_pwd
  slave2:
    image: redis
    container_name: redis-slave-2
    networks:
      - shared    
    ports:
      - 6381:6379
    command: redis-server --slaveof redis-master 6379 --requirepass redis_pwd --masterauth redis_pwd

networks:
  shared: 
    external:
      name: shared
